DROP TABLE MYMEMBER;
DROP SEQUENCE SEQ_MYMEMBER;

CREATE TABLE MYMEMBER(
	MYNO NUMBER PRIMARY KEY, 
	MYID VARCHAR2(500) NOT NULL UNIQUE,
	MYPW VARCHAR2(500) NOT NULL,
	MYNAME VARCHAR2(500) NOT NULL,
	MYADDR VARCHAR2(1000) NOT NULL,
	MYPHONE VARCHAR2(100) NOT NULL UNIQUE,
	MYEMAIL VARCHAR2(100) NOT NULL UNIQUE,
	MYENABLED VARCHAR2(2) NOT NULL CHECK(MYENABLED IN('Y','N')),
	MYROLE VARCHAR2(50) NOT NULL
);

CREATE SEQUENCE SEQ_MYMEMBER NOCACHE;

INSERT INTO MYMEMBER
VALUES(SEQ_MYMEMBER.NEXTVAL, 'ADMIN', 'ADMIN1234', '관리자', '서울시 강남구',
       '010-1234-1234', 'ADMIN@MYMEMEBER.COM', 'Y', 'ADMIN');

SELECT * FROM MYMEMBER;